stages:
  - lint
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip/
    - .venv/

# before_script:
#   - python --version
#   - python -m venv .venv
#   - source .venv/bin/activate
#   - pip install -e .

lint:
  stage: lint
  image: python:3.11
  script:
    - source .venv/bin/activate
    - ruff check .
    - black --check .
    - isort --check .
    - mypy .
  allow_failure: false

test:
  stage: test
  image: python:3.11
  services:
    - name: docker:dind
  before_script:
    - apt-get update -qq && apt-get install -y -qq xvfb
    - python --version
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install -e .
  script:
    - source .venv/bin/activate
    - xvfb-run -a pytest tests/
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    when: always
