stages:
  - lint

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip/
    - .venv/

lint:
  stage: lint
  image: python:3.11
  script:
    # - source .venv/bin/activate
    - ruff check .
    - black --check .
    - isort --check .
    - mypy .
  allow_failure: false
